### ISSUE TITLE
can you upload the paper?

### ISSUE THREAD

**Issue by lslynf** [rootskar/EEGMotorImagery#1]
Thank you for the open source code, but I can't find the paper you mentioned in README file, so can you upload the paper?

**Comment by rootskar** [comment]
Hi!

Thank you for the interest, but the paper is yet to be published. I can let
you know when the paper is published with the link if you'd like.

**Comment by rootskar** [comment]
> Thank you for the open source code, but I can't find the paper you mentioned in README file, so can you upload the paper?

The paper has now been published and is available at https://www.mdpi.com/2073-431X/9/3/72
